version: '3.8'

services:
  java-maven-app:
    container_name: java-maven-app
    image: raffey/java-maven-app:1.1
    ports:
      - 8080:8080
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456